# Generated by Django 5.2.17 on 2026-08-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('project_number', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('production_status', models.CharField(choices=[('ON_DECK', 'On Deck'), ('IN_PROGRESS', 'In Progress'), ('READY_FOR_FINISHING', 'Ready for Finishing'), ('READY_FOR_INSTALL', 'Ready for Install'), ('COMPLETE', 'Complete')], default='ON_DECK', max_length=30)),
            ],
        ),
    ]
